// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJfAw90xrkjquepDHLXETQxS3ForX8b4',
    appId: '1:771614633320:web:19a17e11cf168e796b3add',
    messagingSenderId: '771614633320',
    projectId: 'stylesnap-837b1',
    authDomain: 'stylesnap-837b1.firebaseapp.com',
    storageBucket: 'stylesnap-837b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesNxb_ky1KYZdsTB3fCFGxhao2qp4d44',
    appId: '1:771614633320:android:90fb1f0c50ff9fd06b3add',
    messagingSenderId: '771614633320',
    projectId: 'stylesnap-837b1',
    storageBucket: 'stylesnap-837b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6c50rDX2uUSk_lkjo6cjXpkoOyq6oidg',
    appId: '1:771614633320:ios:4fbcee031d8c85d66b3add',
    messagingSenderId: '771614633320',
    projectId: 'stylesnap-837b1',
    storageBucket: 'stylesnap-837b1.firebasestorage.app',
    iosBundleId: 'com.example.stylesnap',
  );
}
